print('hi')
print('hello')
print('namaste')
print('kem cho')
print('hi')
print('hello')
print('namaste')
print('kem cho')
print('hi')
print('hello')
print('namaste')
print('kem cho')
print('hi')
print('hello')
print('namaste')
print('kem cho')